# slam_toolbox_config.yaml
slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_frame: map
    odom_frame: odom
    base_frame: base          # youâ€™re using 'base', not 'base_link'
    scan_topic: /scan
    mode: mapping             # online mapping
    resolution: 0.05
    max_laser_range: 30.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    transform_publish_period: 0.02